Module5-task1
htmlacademy-react/2192939-six-cities-13 pull request #7
Opened 2023-07-24 07:33 UTC by postfm

2023-07-24 11:26 UTC, n0sfer666 requested changes

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/cities-list/cities-list.tsx
> +type TCitiesListProps = {
"T" в названии излишне. Можно просто CitiesListProps
Много где увидел этот паттерн в проекте. Используйте "поиск и замену" по проекту и исправьте всё.

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/map/map.tsx
> +const currentCustomIcon = new Icon({
Дублирование кода. Создайте функцию типа getIcon = (iconUrl: string) => new Icon({ .... })

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/map/map.tsx
> +  selectedPlace = undefined,
Никогда не присваивайте переменной значение undefined. Этот тип данных используется движком Js.
Значение по-умолчанию null - здесь тоже будет плохим решением.

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/map/map.tsx
> +  selectedPlace?: TOffer | undefined;
? в названии поля итак говорит о том, что может быть undefined

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/map/map.tsx
> +        marker
бессмысленный перенос. Почему не сделали marker.setIcon( ... )?

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/map/map.tsx
> +            selectedPlace !== undefined && selectedPlace.id === offer.id
selectedPlace && selectedPlace.id === offer.id

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/review-card/review-card.tsx
> +    <li className="reviews__item" key={item.id}>
`<li>` всегда должен быть рядом с `<ul>`, иначе если этот компонент будет добавлен в другое место получится бессмыслица в html

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/review-card/review-card.tsx
> +              style={{
Можно написать в одну строчку

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/review-form/review-form.tsx
>    const isReview = !(
1) isReviewed
2) Изменяемые данные должны быть в стейте и пересчитываться либо в useEffect либо в handler'е (-ах)

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/review-form/review-form.tsx
> +    formData.rating && formData.review.length >= MIN_LENGTH_REVIEW_TEXT
Далее у вас идёт дублирование кода с системой рейтинга.
Сделайте вне компонента (перед function ReviewForm ( ... ) {) перенную с массивом изменяемых данных:
```
const ratings = [
  { rating: 5, title: 'perfect' },
  ...
]
```
А внутри div "reviews__rating-form form__rating" сделайте `{ratings.map(({ ratings, title }) => ( ... ))}`

2023-07-24 11:26 UTC, n0sfer666 commented on src/components/reviews-list/reviews-list.tsx
> +          <ReviewCard key={item.id} item={item} />
вот здесь ReviewCard нужно обернуть в <li>

2023-07-24 11:26 UTC, n0sfer666 commented on src/hooks/use-map.tsx
> +  const isRenderedRef = useRef<boolean>(false);
почему реф? По поведение тут обычный useState
```
const [isRendered, setIsRendered] = useState(false);
```

2023-07-24 11:26 UTC, n0sfer666 commented on src/hooks/use-map.tsx
> +    if (mapRef.current !== null && !isRenderedRef.current) {
```
if (mapRef.current && !isRendered) { ... }
```

2023-07-24 12:47 UTC, postfm commented on src/components/map/map.tsx
> +        marker
Так настроен линтер - он форматирует именно так.

2023-07-24 12:50 UTC, postfm commented on src/components/review-card/review-card.tsx
> +              style={{
Опять настройки линтера.

2023-07-24 12:52 UTC, postfm commented on src/components/reviews-list/reviews-list.tsx
> +          <ReviewCard key={item.id} item={item} />
Здесь не понял.

2023-07-24 13:05 UTC, postfm commented on src/components/review-form/review-form.tsx
>    const isReview = !(
Я здесь основывался на теоретическом материале из прошлого раздела.
Вот статья из учебника: https://up.htmlacademy.ru/profession/fullstack/5/react/13/module/4/item/23
...
Какие из них относятся к состоянию приложения, а какие нет? Попробуйте ответить на перечисленные вопросы:

Не изменяются с течением времени? Если да, это не состояние.
Передаются от родителя через пропсы? Если да, это не состояние.
Вычисляются на основе состояния или пропса в компоненте? Если да, это точно не состояние.
...

2023-07-24 13:09 UTC, postfm commented on src/hooks/use-map.tsx
> +  const isRenderedRef = useRef<boolean>(false);
Здесь решение взято из демонстрации https://up.htmlacademy.ru/profession/fullstack/5/react/13/demos/11239#5
слайд №5
Для решения нашей задачи, создадим хук useMap. Внутри него воспользуемся стандартными хуками. Хук useState добавит состояние для нашего пользовательского хука, useEffect — возможность применять побочные эффекты, а useRef поможет защититься от повторной инициализации карты.

2023-07-25 06:20 UTC, n0sfer666 requested changes

2023-07-25 06:20 UTC, n0sfer666 commented on src/components/map/map.tsx
> +        marker
![Screenshot from 2023-07-25 08-40-22](https://github.com/htmlacademy-react/2192939-six-cities-13/assets/21785370/c31afd0d-a423-4fac-9010-daec333fc219)
Учитесь обманывать линтер 😸

2023-07-25 06:20 UTC, n0sfer666 commented on src/components/review-card/review-card.tsx
> +              style={{
![Screenshot from 2023-07-25 08-43-45](https://github.com/htmlacademy-react/2192939-six-cities-13/assets/21785370/02bd2ceb-9eda-432d-ab9b-5810f15fe514)

2023-07-25 06:20 UTC, n0sfer666 commented on src/components/review-form/review-form.tsx
>    const isReview = !(
Ок, проверил. Вы правы.
Но переименовать нужно. Посмотрел что сейчас вы используете это для того чтобы кнопку отключать.
Нужно сделать так:
```
const isReviewed =  rating !== EMPTY_RATING
  && review.length >= MIN_LENGTH_REVIEW_TEXT
  &&review.length <= MAX_LENGTH_REVIEW_TEXT;
```
а там где вы кнопку отключаете, как раз инвертировать
Иначе семантика нарушается. У вас isReviewed = true, когда отзыв невалидный.
PS. Это не моё дело, но 50 символов для отзыва - многовато 🥲

2023-07-25 06:20 UTC, n0sfer666 commented on src/components/reviews-list/reviews-list.tsx
> +          <ReviewCard key={item.id} item={item} />
Вы должны вытащить `<li ...>` из ReviewCard и обернуть им.
Должно получиться так:
```
{review.review.map((item) => (
        <li  key={item.id} className='...'>
          <ReviewCard item={item} />
        </li>
```
А из RevewCard нужно этот тег вытащить.
Запомните раз и навсегда, что список всегда должен быть цельным. Его нельзя разносить по разным компонентам

2023-07-25 06:20 UTC, n0sfer666 commented on src/hooks/use-map.tsx
> +  const isRenderedRef = useRef<boolean>(false);
Да, я видел это решение. Ладно, оставляйте как есть.

2023-07-25 06:44 UTC, postfm commented on src/components/review-card/review-card.tsx
> +              style={{
Здесь я не прав. У меня по умолчанию стоял Prettier

2023-07-25 06:47 UTC, postfm commented on src/components/review-form/review-form.tsx
>    const isReview = !(
50 символов это не моя выдумка - это markup: To submit review please make sure to set rating and describe your stay with at least 50 characters.

2023-07-25 07:24 UTC, merged